name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  PROJECT_DIR: /var/www/snapserve/crm

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Executing remote SSH commands using password
        id: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: cd ${{ env.PROJECT_DIR }} && sh .github/deploy.sh 'production'
